#
# Behat tooling.
#

#
# https://github.com/elgalu/docker-selenium
# for @javascript behat testing
#
selenium:
  image: elgalu/selenium:latest
  volumes:
    - /dev/shm:/dev/shm
  ports:
    - "4444:24444"
    - "5900:25900"
    - "6080:26080"
  privileged: true
  stdin_open: true
  tty: true
  environment:
    TZ: "US/Pacific"
    NOVNC: "true"

behat:
  image: leevh/docker-kalabox-behat:latest
  volumes:
    - $KALABOX_APP_ROOT/code:/srv/code
    - $KALABOX_APP_ROOT/code/behat.yml:/srv/behat.yml
    - $KALABOX_APP_ROOT/code/features:/srv/features
    - $KALABOX_APP_ROOT/config/behat/settings.php:/srv/code/sites/default/settings.php
    - $KALABOX_APP_ROOT/config/behat/usermap.sh:/usr/local/bin/usermap
  working_dir: /srv
  stdin_open: true
  tty: true
  links:
    - db:database
    - selenium:grid
